# Site settings
#key value pair, colon segregated 
title: AVblogs
name: Alexander Moses - Victor Vid
email: alexandermoses88@gmail.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
