# Site settings
#key value pair, colon segregated 
title: Blog test -w- YAML
author: ALEX
name: Evan Will
email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
